#!/usr/bin/env python
"""
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  This file is part of the Smart Developer Hub Project:
    http://www.smartdeveloperhub.org

  Center for Open Middleware
        http://www.centeropenmiddleware.com/
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Copyright (C) 2015 Center for Open Middleware.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
"""

__author__ = 'Alejandro F. Carrera'

from drainer.drainer import app, drainer
import logging

# Main

if __name__ == '__main__':
    logging.info(" * Drainer Started")
    redis_string = " * [LINK] Redis is "
    if drainer.redis is None:
        redis_string += "not available"
    else:
        redis_string += "online"
    logging.info(redis_string + " at http://%s:%d" % (
        app.config.get('REDIS_IP', '127.0.0.1'),
        app.config.get('REDIS_PORT', 6379)
    ))
    git_string = " * [LINK] Gitlab is "
    if drainer.git is None:
        git_string += "not available"
    else:
        git_string += "online"
    logging.info(git_string + " at %s://%s:%d" % (
        app.config.get('GITLAB_PROT', 'http'),
        app.config.get('GITLAB_IP', '127.0.0.1'),
        app.config.get('GITLAB_PORT', 8080)
    ))
    app.run(app.config.get('DRAINER_LISTEN_IP', '0.0.0.0'), app.config.get('DRAINER_PORT', 5000))
